// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// forwardBackwardHMMc
NumericMatrix forwardBackwardHMMc(IntegerVector obs, NumericMatrix transMtx, NumericMatrix emisMtx, NumericVector pi);
RcppExport SEXP _hmm615_forwardBackwardHMMc(SEXP obsSEXP, SEXP transMtxSEXP, SEXP emisMtxSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transMtx(transMtxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type emisMtx(emisMtxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(forwardBackwardHMMc(obs, transMtx, emisMtx, pi));
    return rcpp_result_gen;
END_RCPP
}
// viterbiHMMc
List viterbiHMMc(IntegerVector obs, NumericMatrix transMtx, NumericMatrix emisMtx, NumericVector pi);
RcppExport SEXP _hmm615_viterbiHMMc(SEXP obsSEXP, SEXP transMtxSEXP, SEXP emisMtxSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transMtx(transMtxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type emisMtx(emisMtxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbiHMMc(obs, transMtx, emisMtx, pi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hmm615_forwardBackwardHMMc", (DL_FUNC) &_hmm615_forwardBackwardHMMc, 4},
    {"_hmm615_viterbiHMMc", (DL_FUNC) &_hmm615_viterbiHMMc, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_hmm615(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
