# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Forward-backward algorithm implemented in Rcpp
#'
#' This function implements a forward-backward algorithm of a generic HMM, given observed outcomes, transition and emission matrices, and initial probabilities.
#'
#' @param obs size T integer vector of observed outcomes, values from 1 to m
#' @param transMtx n x n transition matrix from row to column
#' @param emisMtx n x m emission matrix of observed data (column) given states (row)
#' @param pi size n vector of initial state probabilities
#' @return matrix of conditional probability of each state given the observed outcomes
#' @examples 
#' obs <- c(1,3,2)
#' A <- matrix(c(0.8,0.2,0.4,0.6),2,2,byrow=TRUE)
#' B <- matrix(c(0.88,0.10,0.02,0.1,0.6,0.3),2,3,byrow=TRUE)
#' pi <- c(0.7,0.3)
#' forwardBackwardHMMc(obs, A, B, pi)
#' @export
forwardBackwardHMMc <- function(obs, transMtx, emisMtx, pi) {
    .Call('_hmm615_forwardBackwardHMMc', PACKAGE = 'hmm615', obs, transMtx, emisMtx, pi)
}

#' Viterbi algorithm implemented in Rcpp
#'
#' This function implements a Vitervi algorithm in generic HMM, given observed outcomes, transition and emission matrices, and initial probabilities.
#'
#' @param obs size T integer vector of observed outcomes, values from 1 to m
#' @param transMtx n x n transition matrix from row to column
#' @param emisMtx n x m emission matrix of observed data (column) given states (row)
#' @param pi size n vector of initial state probabilities
#' @return a matrix containing conditional probability of each possible states given the observed outcomes
#' @examples 
#' obs <- c(1,3,2)
#' A <- matrix(c(0.8,0.2,0.4,0.6),2,2,byrow=TRUE)
#' B <- matrix(c(0.88,0.10,0.02,0.1,0.6,0.3),2,3,byrow=TRUE)
#' pi <- c(0.7,0.3)
#' viterbiHMMc(obs, A, B, pi)
#' @export
viterbiHMMc <- function(obs, transMtx, emisMtx, pi) {
    .Call('_hmm615_viterbiHMMc', PACKAGE = 'hmm615', obs, transMtx, emisMtx, pi)
}

